### ISSUE TITLE
Impossible to log or creat user

### ISSUE THREAD

**Issue by lillois59** [abdurraufraihan/django-chat#2]
Hi good template great work but unfortuntly after fews setting its not working  or I missed something how to fix it please I mean I can fill the required field name, email ... but the button "Sign Up is not working-clicking : 

$ serve -s build

   ┌────────────────────────────────────────────┐
   │                                            │
   │   Serving!                                 │
   │                                            │
   │   - Local:    http://localhost:3000        │
   │   - Network:  http://192.168.50.253:3000   │
   │                                            │
   │   Copied local address to clipboard!       │
   │                                            │
   └────────────────────────────────────────────┘

 HTTP  01.12.2022 09:25:22 ::1 GET /
 HTTP  01.12.2022 09:25:22 ::1 Returned 200 in 534 ms
 HTTP  01.12.2022 09:25:23 ::1 GET /static/css/main.b38da5c0.css
 HTTP  01.12.2022 09:25:23 ::1 Returned 200 in 18 ms
 HTTP  01.12.2022 09:25:24 ::1 GET /static/js/main.9dee8d89.js

**Comment by abdurraufraihan** [comment]
I guess you haven't started the back-end server before starting the front-end server. Please make sure your back-end server is running before starting front-end.

**Comment by lillois59** [comment]
Hi @abdurraufraihan, happy friday, 

this morning its look the same error followed yours advice : 
creat new virtual-evn : ok 
git clone & jump inside Django-chat/server + sudo pip install -r requirements.txt : ok 
start backend python manage.py runserver : ok 
but can't still logging why the button not clickable :/

**Comment by abdurraufraihan** [comment]
Hello @lillois59 , Happy Friday

I updated instruction into readme. Please follow those steps again.

Thanks regards
Raihan
